radioList()	Generates a list of radio buttons.	yii\helpers\BaseHtml
radioList()	Создает список переключателей.	yii\helpers\BaseHtml

radioList() public static method
radioList() открытый статический метод
Generates a list of radio buttons.
Создает список переключателей.

A radio button list is like a checkbox list, except that it only allows single selection.
Список переключателей похож на список флажков, за иключением того позволяет выбрать только один выбор.

public static string radioList ( $name, $selection = null, $items = [], $options = [] )

$name	string	
The name attribute of each radio button.
Имя атрибута каждого переключателя.

$selection	string|array|null	
The selected value(s). String for single or array for multiple selection(s).
Выбранное значение. Строка для единственного или массив для множественного выбора.

$items	array	
The data item used to generate the radio buttons. The array keys are the radio button values, while the array values are the corresponding labels.
Элементы используются для создания переключателей. Ключи массива являются значением переключателей, а значения массива - соответствующие метки.

$options	array	
Options (name => config) for the radio button list container tag. The following options are specially handled:
Опции (имя => конфигурация) для тегов списка переключателей. Особо обрабатываются следующие параметры:

tag: string|false, the tag name of the container element. False to render radio buttons without container. See also tag().
тэг: строка|false, имя тега контейнера элемента. Ложное значение создает переключатели без контейнера. Смотрите также метод tag().

unselect: string, the value that should be submitted when none of the radio buttons is selected. By setting this option, a hidden input will be generated.
невыбранный: строка, значение которое должно быть отправлено, когда переключатель не выбран. Установив этот параметр, будет сгенерирован скрытый тег input.

disabled: boolean, whether the generated by unselect option hidden input should be disabled. Defaults to false. This option is available since version 2.0.16.
отключен: boolean, должен ли быть отображен параметр disabled в hidden input. По умолчанию ложное значение (не отображается). Эта опция доступна с версии 2.0.16.
коментарий автора: скорей всего отображение/не отображение disabled нужно для JS.

encode: boolean, whether to HTML-encode the checkbox labels. Defaults to true. This option is ignored if item option is set.
кодировать: boolean, кодировать ли в HTML метки флажков. По умолчанию истина. Эта опция игнорируется для выбранных элементов.

strict: boolean, if $selection is an array and this value is true a strict comparison will be performed on $items keys. Defaults to false. This option is available since 2.0.37.
точный: boolean, если параметр selection - массив и этот параметр имеет истинное значение точное сравнение будет выполненно с ключами items. По умолчанию ложное значение (не отображается). Эта опция доступна с версии 2.0.16.

separator: string, the HTML code that separates items.
разделитель: строка, HMTL код - разделитель элементов.

itemOptions: array, the options for generating the radio button tag using radio().
опции элементов: массив, опции для создания тегов переключателей использую метод radio().

item: callable, a callback that can be used to customize the generation of the HTML code corresponding to a single item in $items. The signature of this callback must be:
элемент: фукнция обратного вызова, вызов функции, который можно использовать для настройки создания HTML кода, соответсвующего одному элементу в $items. Функция обратного вызова должна быть:

function ($index, $label, $name, $checked, $value)

where $index is the zero-based index of the radio button in the whole list; $label is the label for the radio button; and $name, $value and $checked represent the name, value and the checked status of the radio button input, respectively.
где $index это отсчитываемый от нуля индекс переключателя во всем списке; $label - метка для переключателя; $name, $value и $checked представляют имя, значение и нажат ли переключатель, соответственно.

See renderTagAttributes() for details on how attributes are being rendered.
См. RenderTagAttributes () для получения подробной информации о том, как отображаются атрибуты.

return	string	
The generated radio button list
Создание списка переключателей
